language: node_js
node_js: "node"
branches:
  only:
  - master
cache:
  directories:
    - node_modules

script:
  - npm run export

deploy:
  - provider: script
    script: cp now.json ./out/ && cd ./out && npx now --public -t $NOW_T && npx now -t $NOW_T alias
    skip_cleanup: true
